import 'package:uuid/uuid.dart';

/// The `TxRefRandomGenerator` class is used for generating transaction reference.
///
class TxRefRandomGenerator {
  TxRefRandomGenerator._();

  /// The generated transaction reference.
  ///
  /// This variable stores the last generated transaction reference.
  static String _txRef = "";

  /// Returns the transaction reference generated by the `TxRefRandomGenerator` class.
  ///
  /// This getter provides access to the transaction reference generated by the `TxRefRandomGenerator` class.
  /// It returns a string representing the transaction reference
  static String get gettxRef => _txRef;

  /// Generates a random transaction reference.
  ///
  /// This method generates a random transaction reference by using UUID.
  /// The generated transaction reference is stored in the [txRef] variable and also returned.
  static String generate() {
    const uuid = Uuid();
    _txRef = uuid.v4(
      options: {'time': DateTime.now().millisecondsSinceEpoch}
    );
    return _txRef;
  }
}
