import 'dart:math';

/// The `TxRefRandomGenerator` class is used for generating transaction references for testing purposes.
///
/// WARNING: This class should NOT be used in a production environment.
class TxRefRandomGenerator {
  /// The generated transaction reference.
  ///
  /// This variable stores the last generated transaction reference.
  static String _txRef = "";

  /// Returns the transaction reference generated by the `TxRefRandomGenerator` class.
  ///
  /// This getter provides access to the transaction reference generated by the `TxRefRandomGenerator` class.
  /// It returns a string representing the transaction reference
  static String get gettxRef => _txRef;

  /// Generates a random transaction reference.
  ///
  /// This method generates a random transaction reference by appending a random number to the prefix "Pharmabet-".
  /// The generated transaction reference is stored in the [txRef] variable and also returned.
  static String generate({String? prefix}) {
    final random = Random();
    _txRef = '${prefix ?? "test"}-${random.nextInt(200)}';
    return _txRef;
  }
}
